### PR TITLE
v1.0.1 version bump and changelog update

### PR DESCRIPTION
**Pull request by ross**
## v1.0.1 - 2023-06-19 - The first one in the CHANGELOG

* Add pytest.mark.network to test cases
* pyproject.toml config for black, isort, and pytest

### CODE REVIEW

**Comment by kloczek** [comment]
If may I ask to remember about yet another small thing.
Is it possible next time on release new version make the github release to have entry on https://github.com/john-kurkowski/tldextract/releases? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.

**Comment by ross** [comment]
> Is it possible next time on release new version make the github release to have entry on https://github.com/john-kurkowski/tldextract/releases? 🤔

Not sure what that repo has to do with requests-futures, but it looks like it's doing the same release tagging as I am here, https://github.com/john-kurkowski/tldextract/tags

Haven't looked into uploading actual release artifacts to github since pypi is the standard/meaningful place for python modules. https://pypi.org/project/requests-futures/#history. Seems kind of annoying to have to push the release to github just to get the notifications. It looks like pypi has the ability to do release notifications https://pypi.org/help/#project-release-notifications and supports RSS feeds as well (both links off the history page above.)

**Comment by kloczek** [comment]
> Not sure what that repo has to do with requests-futures, but it looks like it's doing the same release tagging as I am here, https://github.com/john-kurkowski/tldextract/tags

It is different thing.
Please have a look on https://github.com/john-kurkowski/tldextract/releases
That tab is empty.

**Comment by ross** [comment]
> It is different thing.
> Please have a look on https://github.com/john-kurkowski/tldextract/releases
> That tab is empty.

When I follow that link the page is empty/there are no releases. That package, whatever it is, is not using github releases. 

Screen Shot 2023-06-19 at 2 32 06 PM

**Pull request merged**
